#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Constraints_Constraint */

#ifndef _Included_ChipmunkJava_Constraints_Constraint
#define _Included_ChipmunkJava_Constraints_Constraint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_Constraint_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_Constraint_free
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    _getBodyA
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_Constraint__1getBodyA
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    _getBodyB
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_Constraint__1getBodyB
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    getCollideBodies
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ChipmunkJava_Constraints_Constraint_getCollideBodies
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    getErrorBias
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_Constraint_getErrorBias
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    getImpulse
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_Constraint_getImpulse
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    getMaxBias
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_Constraint_getMaxBias
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    getMaxForce
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_Constraint_getMaxForce
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    _getSpace
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_Constraint__1getSpace
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    setCollideBodies
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_Constraint_setCollideBodies
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    setErrorBias
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_Constraint_setErrorBias
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    setMaxBias
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_Constraint_setMaxBias
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_Constraint
 * Method:    setMaxForce
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_Constraint_setMaxForce
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
