#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Constraints_DampedSpring */

#ifndef _Included_ChipmunkJava_Constraints_DampedSpring
#define _Included_ChipmunkJava_Constraints_DampedSpring
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_DampedSpring_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    _new
 * Signature: (LChipmunkJava/Body;LChipmunkJava/Body;[D[DDDD)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_DampedSpring__1new
  (JNIEnv *, jclass, jobject, jobject, jdoubleArray, jdoubleArray, jdouble, jdouble, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    _clone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_DampedSpring__1clone
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    _getAnchorA
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Constraints_DampedSpring__1getAnchorA
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    _getAnchorB
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Constraints_DampedSpring__1getAnchorB
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    getDamping
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_DampedSpring_getDamping
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    getRestLength
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_DampedSpring_getRestLength
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    getStiffness
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_DampedSpring_getStiffness
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    _setAnchorA
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_DampedSpring__1setAnchorA
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    _setAnchorB
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_DampedSpring__1setAnchorB
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    setDamping
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_DampedSpring_setDamping
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    setRestLength
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_DampedSpring_setRestLength
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_DampedSpring
 * Method:    setStiffness
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_DampedSpring_setStiffness
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
