#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Constraints_GrooveJoint */

#ifndef _Included_ChipmunkJava_Constraints_GrooveJoint
#define _Included_ChipmunkJava_Constraints_GrooveJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Constraints_GrooveJoint
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_GrooveJoint_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Constraints_GrooveJoint
 * Method:    _new
 * Signature: (LChipmunkJava/Body;LChipmunkJava/Body;[D[D[D)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_GrooveJoint__1new
  (JNIEnv *, jclass, jobject, jobject, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_GrooveJoint
 * Method:    _clone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_GrooveJoint__1clone
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_GrooveJoint
 * Method:    _getAnchorB
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Constraints_GrooveJoint__1getAnchorB
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_GrooveJoint
 * Method:    _getGrooveA
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Constraints_GrooveJoint__1getGrooveA
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_GrooveJoint
 * Method:    _getGrooveB
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Constraints_GrooveJoint__1getGrooveB
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_GrooveJoint
 * Method:    _setAnchorB
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_GrooveJoint__1setAnchorB
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_GrooveJoint
 * Method:    _setGrooveA
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_GrooveJoint__1setGrooveA
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_GrooveJoint
 * Method:    _setGrooveB
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_GrooveJoint__1setGrooveB
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
