#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Constraints_GearJoint */

#ifndef _Included_ChipmunkJava_Constraints_GearJoint
#define _Included_ChipmunkJava_Constraints_GearJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Constraints_GearJoint
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_GearJoint_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Constraints_GearJoint
 * Method:    _new
 * Signature: (LChipmunkJava/Body;LChipmunkJava/Body;DD)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_GearJoint__1new
  (JNIEnv *, jclass, jobject, jobject, jdouble, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_GearJoint
 * Method:    _clone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_GearJoint__1clone
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_GearJoint
 * Method:    getPhase
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_GearJoint_getPhase
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_GearJoint
 * Method:    getRatio
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_GearJoint_getRatio
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_GearJoint
 * Method:    setPhase
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_GearJoint_setPhase
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_GearJoint
 * Method:    setRatio
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_GearJoint_setRatio
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
