#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Constraints_PivotJoint */

#ifndef _Included_ChipmunkJava_Constraints_PivotJoint
#define _Included_ChipmunkJava_Constraints_PivotJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Constraints_PivotJoint
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_PivotJoint_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Constraints_PivotJoint
 * Method:    _new
 * Signature: (LChipmunkJava/Body;LChipmunkJava/Body;[D)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_PivotJoint__1new
  (JNIEnv *, jclass, jobject, jobject, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_PivotJoint
 * Method:    _new2
 * Signature: (LChipmunkJava/Body;LChipmunkJava/Body;[D[D)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_PivotJoint__1new2
  (JNIEnv *, jclass, jobject, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_PivotJoint
 * Method:    _clone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_PivotJoint__1clone
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_PivotJoint
 * Method:    _getAnchorA
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Constraints_PivotJoint__1getAnchorA
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_PivotJoint
 * Method:    _getAnchorB
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Constraints_PivotJoint__1getAnchorB
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_PivotJoint
 * Method:    _setAnchorA
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_PivotJoint__1setAnchorA
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_PivotJoint
 * Method:    _setAnchorB
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_PivotJoint__1setAnchorB
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
