#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Constraints_PinJoint */

#ifndef _Included_ChipmunkJava_Constraints_PinJoint
#define _Included_ChipmunkJava_Constraints_PinJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Constraints_PinJoint
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_PinJoint_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Constraints_PinJoint
 * Method:    _new
 * Signature: (LChipmunkJava/Body;LChipmunkJava/Body;[D[D)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_PinJoint__1new
  (JNIEnv *, jclass, jobject, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_PinJoint
 * Method:    _clone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_PinJoint__1clone
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_PinJoint
 * Method:    _getAnchorA
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Constraints_PinJoint__1getAnchorA
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_PinJoint
 * Method:    _getAnchorB
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Constraints_PinJoint__1getAnchorB
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_PinJoint
 * Method:    getDistance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_PinJoint_getDistance
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_PinJoint
 * Method:    _setAnchorA
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_PinJoint__1setAnchorA
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_PinJoint
 * Method:    _setAnchorB
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_PinJoint__1setAnchorB
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_PinJoint
 * Method:    setDistance
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_PinJoint_setDistance
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
