#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Constraints_RatchetJoint */

#ifndef _Included_ChipmunkJava_Constraints_RatchetJoint
#define _Included_ChipmunkJava_Constraints_RatchetJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Constraints_RatchetJoint
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_RatchetJoint_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Constraints_RatchetJoint
 * Method:    _new
 * Signature: (LChipmunkJava/Body;LChipmunkJava/Body;DD)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_RatchetJoint__1new
  (JNIEnv *, jclass, jobject, jobject, jdouble, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_RatchetJoint
 * Method:    _clone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_RatchetJoint__1clone
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_RatchetJoint
 * Method:    getAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_RatchetJoint_getAngle
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_RatchetJoint
 * Method:    getPhase
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_RatchetJoint_getPhase
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_RatchetJoint
 * Method:    getRatchet
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_RatchetJoint_getRatchet
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_RatchetJoint
 * Method:    setAngle
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_RatchetJoint_setAngle
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_RatchetJoint
 * Method:    setPhase
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_RatchetJoint_setPhase
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_RatchetJoint
 * Method:    setRatchet
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_RatchetJoint_setRatchet
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
