#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Constraints_SlideJoint */

#ifndef _Included_ChipmunkJava_Constraints_SlideJoint
#define _Included_ChipmunkJava_Constraints_SlideJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Constraints_SlideJoint
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_SlideJoint_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Constraints_SlideJoint
 * Method:    _new
 * Signature: (LChipmunkJava/Body;LChipmunkJava/Body;[D[DDD)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_SlideJoint__1new
  (JNIEnv *, jclass, jobject, jobject, jdoubleArray, jdoubleArray, jdouble, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_SlideJoint
 * Method:    _clone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_SlideJoint__1clone
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_SlideJoint
 * Method:    _getAnchorA
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Constraints_SlideJoint__1getAnchorA
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_SlideJoint
 * Method:    _getAnchorB
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Constraints_SlideJoint__1getAnchorB
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_SlideJoint
 * Method:    getMax
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_SlideJoint_getMax
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_SlideJoint
 * Method:    getMin
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_SlideJoint_getMin
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_SlideJoint
 * Method:    _setAnchorA
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_SlideJoint__1setAnchorA
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_SlideJoint
 * Method:    _setAnchorB
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_SlideJoint__1setAnchorB
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ChipmunkJava_Constraints_SlideJoint
 * Method:    setMax
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_SlideJoint_setMax
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_SlideJoint
 * Method:    setMin
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_SlideJoint_setMin
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
