#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Constraints_SimpleMotor */

#ifndef _Included_ChipmunkJava_Constraints_SimpleMotor
#define _Included_ChipmunkJava_Constraints_SimpleMotor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Constraints_SimpleMotor
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_SimpleMotor_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Constraints_SimpleMotor
 * Method:    _new
 * Signature: (LChipmunkJava/Body;LChipmunkJava/Body;D)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_SimpleMotor__1new
  (JNIEnv *, jclass, jobject, jobject, jdouble);

/*
 * Class:     ChipmunkJava_Constraints_SimpleMotor
 * Method:    _clone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Constraints_SimpleMotor__1clone
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_SimpleMotor
 * Method:    getRate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Constraints_SimpleMotor_getRate
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Constraints_SimpleMotor
 * Method:    setRate
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Constraints_SimpleMotor_setRate
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
