/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.2.1/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    `java-library`
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

tasks.create<Exec>("copyChipmunkJni_dll") {
	commandLine("./copyChipmunkJni_dll.cmd")
}

tasks.named<JavaCompile>("compileJava") {
	dependsOn(":copyChipmunkJni_dll")
}

tasks.withType<Test>() {
    systemProperty("java.library.path", "build/libs")
}

