#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Collisions_CollisionSet */

#ifndef _Included_ChipmunkJava_Collisions_CollisionSet
#define _Included_ChipmunkJava_Collisions_CollisionSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Collisions_CollisionSet
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_CollisionSet_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Collisions_CollisionSet
 * Method:    _new
 * Signature: (LChipmunkJava/Space;LChipmunkJava/Collisions/CollisionType;LChipmunkJava/Collisions/CollisionType;)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Collisions_CollisionSet__1new
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     ChipmunkJava_Collisions_CollisionSet
 * Method:    _disableBeginCollisionHandler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_CollisionSet__1disableBeginCollisionHandler
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Collisions_CollisionSet
 * Method:    _enableBeginCollisionHandler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_CollisionSet__1enableBeginCollisionHandler
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Collisions_CollisionSet
 * Method:    _disablePreSolveCollisionHandler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_CollisionSet__1disablePreSolveCollisionHandler
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Collisions_CollisionSet
 * Method:    _enablePreSolveCollisionHandler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_CollisionSet__1enablePreSolveCollisionHandler
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Collisions_CollisionSet
 * Method:    _disablePostSolveCollisionHandler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_CollisionSet__1disablePostSolveCollisionHandler
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Collisions_CollisionSet
 * Method:    _enablePostSolveCollisionHandler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_CollisionSet__1enablePostSolveCollisionHandler
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Collisions_CollisionSet
 * Method:    _disableSeparateCollisionHandler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_CollisionSet__1disableSeparateCollisionHandler
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Collisions_CollisionSet
 * Method:    _enableSeparateCollisionHandler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_CollisionSet__1enableSeparateCollisionHandler
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
