#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Collisions_CollisionType */

#ifndef _Included_ChipmunkJava_Collisions_CollisionType
#define _Included_ChipmunkJava_Collisions_CollisionType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Collisions_CollisionType
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_CollisionType_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Collisions_CollisionType
 * Method:    cpCollisionTypeGetWildcard
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Collisions_CollisionType_cpCollisionTypeGetWildcard
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
