#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Collisions_ShapeQueryInfo */

#ifndef _Included_ChipmunkJava_Collisions_ShapeQueryInfo
#define _Included_ChipmunkJava_Collisions_ShapeQueryInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Collisions_ShapeQueryInfo
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_ShapeQueryInfo_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Collisions_ShapeQueryInfo
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_ShapeQueryInfo_free
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Collisions_ShapeQueryInfo
 * Method:    _getContactPointSet
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Collisions_ShapeQueryInfo__1getContactPointSet
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Collisions_ShapeQueryInfo
 * Method:    _getShape
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Collisions_ShapeQueryInfo__1getShape
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
