#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Collisions_ShapeFilter */

#ifndef _Included_ChipmunkJava_Collisions_ShapeFilter
#define _Included_ChipmunkJava_Collisions_ShapeFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Collisions_ShapeFilter
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Collisions_ShapeFilter_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Collisions_ShapeFilter
 * Method:    getNoCollisionGroup
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Collisions_ShapeFilter_getNoCollisionGroup
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Collisions_ShapeFilter
 * Method:    getAllCollisionCategories
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ChipmunkJava_Collisions_ShapeFilter_getAllCollisionCategories
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
