#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Shapes_CircleShape */

#ifndef _Included_ChipmunkJava_Shapes_CircleShape
#define _Included_ChipmunkJava_Shapes_CircleShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Shapes_CircleShape
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Shapes_CircleShape_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Shapes_CircleShape
 * Method:    _new
 * Signature: (LChipmunkJava/Body;D[D)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Shapes_CircleShape__1new
  (JNIEnv *, jclass, jobject, jdouble, jdoubleArray);

/*
 * Class:     ChipmunkJava_Shapes_CircleShape
 * Method:    _clone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Shapes_CircleShape__1clone
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Shapes_CircleShape
 * Method:    _getOffset
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Shapes_CircleShape__1getOffset
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Shapes_CircleShape
 * Method:    getRadius
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Shapes_CircleShape_getRadius
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Shapes_CircleShape
 * Method:    _setOffset
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Shapes_CircleShape__1setOffset
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ChipmunkJava_Shapes_CircleShape
 * Method:    setRadius
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Shapes_CircleShape_setRadius
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
