#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Shapes_SegmentShape */

#ifndef _Included_ChipmunkJava_Shapes_SegmentShape
#define _Included_ChipmunkJava_Shapes_SegmentShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Shapes_SegmentShape
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Shapes_SegmentShape_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Shapes_SegmentShape
 * Method:    _new
 * Signature: (LChipmunkJava/Body;[D[DD)J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Shapes_SegmentShape__1new
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     ChipmunkJava_Shapes_SegmentShape
 * Method:    _clone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ChipmunkJava_Shapes_SegmentShape__1clone
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Shapes_SegmentShape
 * Method:    _getPointA
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Shapes_SegmentShape__1getPointA
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Shapes_SegmentShape
 * Method:    _getPointB
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Shapes_SegmentShape__1getPointB
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Shapes_SegmentShape
 * Method:    _getNormal
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ChipmunkJava_Shapes_SegmentShape__1getNormal
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Shapes_SegmentShape
 * Method:    getRadius
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Shapes_SegmentShape_getRadius
  (JNIEnv *, jobject);

/*
 * Class:     ChipmunkJava_Shapes_SegmentShape
 * Method:    _setEndpoints
 * Signature: ([D[D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Shapes_SegmentShape__1setEndpoints
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     ChipmunkJava_Shapes_SegmentShape
 * Method:    setRadius
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Shapes_SegmentShape_setRadius
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
