#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_BodyType */

#ifndef _Included_ChipmunkJava_BodyType
#define _Included_ChipmunkJava_BodyType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_BodyType
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_BodyType_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_BodyType
 * Method:    cpBodyTypeGetDynamic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ChipmunkJava_BodyType_cpBodyTypeGetDynamic
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_BodyType
 * Method:    cpBodyTypeGetKinematic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ChipmunkJava_BodyType_cpBodyTypeGetKinematic
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_BodyType
 * Method:    cpBodyTypeGetStatic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ChipmunkJava_BodyType_cpBodyTypeGetStatic
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
