#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChipmunkJava_Chipmunk */

#ifndef _Included_ChipmunkJava_Chipmunk
#define _Included_ChipmunkJava_Chipmunk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChipmunkJava_Chipmunk
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChipmunkJava_Chipmunk_init
  (JNIEnv *, jclass);

/*
 * Class:     ChipmunkJava_Chipmunk
 * Method:    areaForCircle
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Chipmunk_areaForCircle
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     ChipmunkJava_Chipmunk
 * Method:    _areaForPoly
 * Signature: ([DD)D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Chipmunk__1areaForPoly
  (JNIEnv *, jclass, jdoubleArray, jdouble);

/*
 * Class:     ChipmunkJava_Chipmunk
 * Method:    _areaForSegment
 * Signature: ([D[DD)D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Chipmunk__1areaForSegment
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     ChipmunkJava_Chipmunk
 * Method:    _momentForCircle
 * Signature: (DDD[D)D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Chipmunk__1momentForCircle
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdoubleArray);

/*
 * Class:     ChipmunkJava_Chipmunk
 * Method:    momentForBox
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Chipmunk_momentForBox
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     ChipmunkJava_Chipmunk
 * Method:    _momentForPoly
 * Signature: (D[D[DD)D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Chipmunk__1momentForPoly
  (JNIEnv *, jclass, jdouble, jdoubleArray, jdoubleArray, jdouble);

/*
 * Class:     ChipmunkJava_Chipmunk
 * Method:    _momentForSegment
 * Signature: (D[D[DD)D
 */
JNIEXPORT jdouble JNICALL Java_ChipmunkJava_Chipmunk__1momentForSegment
  (JNIEnv *, jclass, jdouble, jdoubleArray, jdoubleArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
